apiVersion: v1
data:
  default.conf: |+
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/ssl/certs/tls.crt;
        ssl_certificate_key /etc/ssl/certs/tls.key;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }

kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"default.conf":"server {\n    listen 443 ssl;\n    server_name localhost;\n\n    ssl_certificate /etc/ssl/certs/tls.crt;\n    ssl_certificate_key /etc/ssl/certs/tls.key;\n\n    location / {\n        root /usr/share/nginx/html;\n        index index.html;\n    }\n}\n\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"myapp-conf","namespace":"dev"}}
  creationTimestamp: "2026-02-08T06:46:57Z"
  name: myapp-conf
  namespace: dev
  resourceVersion: "27287"
  uid: cd9a8fa7-e4d6-43a3-a902-0fc462d479ec
