apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: poojaganvir2607/myapp:BUILD_NUMBER
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
          - name: tls-volume
            mountPath: /etc/ssl/certs
            readOnly: true
      volumes:
        - name: tls-volume
          hostPath:
            path: /etc/ssl/mycert
            type: Directory



