apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: poojaganvir2607/myapp:BUILD_NUMBER
        imagePullPolicy: Always
        ports:
        - containerPort: 443
        volumeMounts:
          - name: tls-secret
            mountPath: /etc/nginx/tls
            readOnly: true

          - name: nginx-config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
            readOnly: true

      volumes:
        - name: tls-secret
          secret:
            secretName: myapp-secret
        - name: nginx-config
          configMap:
            name: myapp-conf



