replicaCount: 2

image:
  repository: poojaganvir2607/myapp
  tag: ""        # Jenkins will set this dynamically
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  nodePort: 30080
# Add this to fix the nil pointer error
serviceAccount:
  create: false
  name: myapp-serviceaccount
ingress:
  enabled: false   # just disable it
